Models/BusquedaView.cs
using System;

namespace Inmobiliaria.Models
{
    public class BusquedaView
    {
        public DateTime FechaInicio { get; set; }
        public DateTime FechaFin { get; set; }
    }
}

Models/Contrato.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Inmobiliaria.Models
{
    public class Contrato
    {
        [Key]
        [Display(Name = "Código Contrato")]
        public int idContrato { get; set; }
                
        public int idInquilino { get; set; }
        [ForeignKey("idInquilino")]

        public Inquilino Inquilinos { get; set; }

        public int idInmueble { get; set; }
        [ForeignKey("idInmueble")]


        public Inmueble Inmuebles { get; set; }

        [Display(Name = "Fecha Inicio")]
        public DateTime FechaInicio { get; set; }

        [Display(Name = "Fecha Final")]
        public DateTime FechaFin { get; set; }

        [Display(Name = "$ Alquiler")]
        public decimal MontoAlquiler { get; set; }
        public bool Vigente { get; set; }
    }
}

Controllers/ContratosController.cs
using Inmobiliaria.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;

namespace Inmobiliaria.Controllers
{
    [Authorize]
    public class ContratosController : Controller
    {
        private readonly IConfiguration configuration;
        private readonly RepositorioInmueble repositorioInmuebles;
        private readonly RepositorioInquilino repositorioInquilinos;
        private readonly RepositorioContrato repositorioContratos;

        public ContratosController(IConfiguration configuration)
        {
            this.configuration = configuration;
            repositorioInmuebles = new RepositorioInmueble(configuration);
            repositorioInquilinos = new RepositorioInquilino(configuration);
            repositorioContratos = new RepositorioContrato(configuration);
        }
        // GET: Contratos
        [Authorize(Policy = "Permitidos")]
        public ActionResult Index()
        {
            var lista = repositorioContratos.ObtenerTodos();
            if (TempData.ContainsKey("Id"))
                ViewBag.Id = TempData["Id"];
            if (TempData.ContainsKey("Mensaje"))
                ViewBag.Mensaje = TempData["Mensaje"];
            return View(lista);
        }

        // GET: Contratos/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Contratos/Create
        [Authorize(Policy = "Permitidos")]
        public ActionResult Create(int id)
        {
            ViewBag.Inmuebles = repositorioInmuebles.ObtenerPorId(id);
            ViewBag.Inquilinos = repositorioInquilinos.ObtenerTodos();
            return View();
        }

        // POST: Contratos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Permitidos")]
        public ActionResult Create(Contrato c)
        {
            try
            {
                // TODO: Add insert logic here
                int res = repositorioContratos.Alta(c);
                Inmueble inm = repositorioInmuebles.ObtenerPorId(c.idInmueble);
                repositorioContratos.Vigente(c);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Inquilinos = repositorioInquilinos.ObtenerTodos();
                ViewBag.Error = ex.Message;
                return RedirectToAction(nameof(Index));
            }
        }
        public ActionResult Ver(int id)
        {
            try
            {
                ViewBag.Id = id;
                var lista = repositorioContratos.ObtenerTodosPorInm(id);
                return View(lista);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();

            }
        }

        // GET: Contratos/Edit/5
        [Authorize(Policy = "Permitidos")]
        public ActionResult Edit(int id)
        {
            var i = repositorioContratos.ObtenerPorId(id);
            ViewBag.Inquilinos = repositorioInquilinos.ObtenerTodos();
            if (TempData.ContainsKey("Mensaje"))
                ViewBag.Mensaje = TempData["Mensaje"];
            if (TempData.ContainsKey("Error"))
                ViewBag.Error = TempData["Error"];
            return View(i);
        }

        // POST: Contratos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Permitidos")]
        public ActionResult Edit(int id, Contrato c)
        {
            try
            {
                c.idContrato = id;
                repositorioContratos.Modificacion(c);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Inquilinos = repositorioInquilinos.ObtenerTodos();
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View(c);
            }
        }

        // GET: Contratos/Delete/5
        [Authorize(Policy = "Administrador")]
        public ActionResult Delete(int id)
        {
            var c = repositorioContratos.ObtenerPorId(id);
            if (TempData.ContainsKey("Mensaje"))
                ViewBag.Mensaje = TempData["Mensaje"];
            if (TempData.ContainsKey("Error"))
                ViewBag.Error = TempData["Error"];
            return View(c);
        }

        // POST: Contratos/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Administrador")]
        public ActionResult Delete(int id, Contrato c)
        {
            try
            {
                repositorioContratos.Baja(id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View(c);
            }
        }
        public ActionResult Filtrados()
        {
            return View();
        }
        public ActionResult Busqueda()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Busqueda(PorFechaView busqueda)
        {
            try
            {

                ViewBag.Filtrados = repositorioContratos.VigentesPorFecha(busqueda.FechaBusqueda);
                if (ViewBag.Filtrados.Count == 0)
                {
                    ModelState.AddModelError("", "No se encontraron resultados");
                    return View();
                }
                return View("Filtrados");

            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }
    }
}

Controllers/PagosController.cs
using Inmobiliaria.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

namespace Inmobiliaria.Controllers
{
    [Authorize]
    public class PagosController : Controller
    {
        private readonly IConfiguration configuration;
        private readonly RepositorioContrato repositorioContratos;
        private readonly RepositorioPago repositorioPagos;
        private readonly RepositorioInmueble repositorioInmuebles;

        public PagosController(IConfiguration configuration)
        {
            this.configuration = configuration;
            repositorioContratos = new RepositorioContrato(configuration);
            repositorioPagos = new RepositorioPago(configuration);
            repositorioInmuebles = new RepositorioInmueble(configuration);
        }
        // GET: Pagos
        [Authorize(Policy = "Permitidos")]
        public ActionResult Index()
        {
            var lista = repositorioPagos.ObtenerTodos();
            return View(lista);
        }

        // GET: Pagos/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Pagos/Create
        [Authorize(Policy = "Permitidos")]
        public ActionResult Create(int id)
        {
            ViewBag.Contratos = repositorioContratos.ObtenerPorInm(id);
            Contrato c = repositorioContratos.ObtenerPorInm(id);
            IList<Pago> pagos = repositorioPagos.ObtenerPorContr(c.idContrato);
            if (pagos.Count == 0)
            {
                ViewBag.Numero = 1;
            }
            else
            {
                int np = pagos.Count;
                ViewBag.Numero = np + 1;
            }

            return View();
        }

        // POST: Pagos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Permitidos")]
        public ActionResult Create(Pago p)
        {
            try
            {
                int res = repositorioPagos.Alta(p);
                return RedirectToAction(nameof(Ver), new { id = p.idContrato });
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }
        [Authorize(Policy = "Permitidos")]
        public ActionResult Ver(int id)
        {
            ViewBag.Contratos = repositorioContratos.ObtenerPorId(id);
            IList<Pago> pagos = repositorioPagos.ObtenerPorContr(id);
            return View(pagos);
        }

        // GET: Pagos/Edit/5
        [Authorize(Policy = "Permitidos")]
        public ActionResult Edit(int id)
        {
            var p = repositorioPagos.ObtenerPorId(id);
            return View(p);

        }

        // POST: Pagos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Permitidos")]
        public ActionResult Edit(int id, Pago p)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int res = repositorioPagos.Modificacion(p);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View();
                }

            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }


        // GET: Pagos/Delete/5
        [Authorize(Policy = "Administrador")]
        public ActionResult Delete(int id)
        {
            var p = repositorioPagos.ObtenerPorId(id);
            if (TempData.ContainsKey("Mensaje"))
                ViewBag.Mensaje = TempData["Mensaje"];
            if (TempData.ContainsKey("Error"))
                ViewBag.Error = TempData["Error"];
            return View(p);
        }

        // POST: Pagos/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Administrador")]
        public ActionResult Delete(int id, Pago p)
        {
            try
            {
                repositorioPagos.Baja(id);
                return RedirectToAction(nameof(Index));


            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View(p);
            }
        }
    }
}

Views/Contratos/Busqueda.cshtml
@model Inmobiliaria.Models.PorFechaView

@{ ViewData["Title"] = "Busqueda"; }

<h2>Busqueda por Fecha</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Busqueda">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FechaBusqueda" class="control-label">Fecha de Busqueda</label>
                <input asp-for="FechaBusqueda" type="date" class="form-control" />
                <span asp-validation-for="FechaBusqueda" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Buscar" class="btn btn-success" />  |
                <a class="btn btn-secondary" asp-action="Index">Cancelar</a>
            </div>
        </form>
    </div>
</div>

Views/Contratos/Create.cshtml
@model Inmobiliaria.Models.Contrato

@{ ViewData["Title"] = "Crear"; }

<h2>Nuevo Contrato</h2>

<h6 class="alert alert-info">Inmueble de tipo: @ViewBag.Inmuebles.Tipo ubicado en: @ViewBag.Inmuebles.Direccion</h6>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="idInmueble" class="control-label"></label>
                <input asp-for="idInmueble" value=@ViewBag.Inmuebles.idInmueble readonly />
                <span asp-validation-for="idInmueble" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Inquilinos</label>
                <select class="form-control" name="IdInq">
                    @foreach (var item in (IList<Inquilino>)ViewBag.Inquilinos)
                    {
        <option value="@item.idInquilino">@(item.Nombre + " " + item.Apellido)</option>
}
                </select>
                <span asp-validation-for="idInquilino" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="control-label">Fecha Inicio</label>
                <input asp-for="FechaInicio" type="date" class="form-control" />
                <span asp-validation-for="FechaInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Fecha Final</label>
                <input asp-for="FechaFin" type="date" class="form-control" />
                <span asp-validation-for="FechaFin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MontoAlquiler" class="control-label"> $ Alquiler</label>
                <input asp-for="MontoAlquiler" value=@ViewBag.Inmuebles.Precio readonly />
                <span asp-validation-for="MontoAlquiler" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Crear Contrato" class="btn btn-success" />
                <a class="btn btn-info" asp-action="Index">Regresar</a>
            </div>
        </form>
    </div>
</div>

Views/Contratos/Delete.cshtml
@model Inmobiliaria.Models.Contrato

@{ ViewData["Title"] = "Eliminar Contrato"; }

<p>

    <h2>Eliminar Contrato</h2>

    <h6 class="alert alert-warning"> Usted esta seguro que desea Eliminar el Contrato ???</h6>
</p>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            <label>Codigo Contrato</label>
        </dt>
        <dd>
            @Html.DisplayFor(model => model.idContrato)
        </dd>
        <dt>
            <label>Codigo Inquilino</label>
        </dt>
        <dd>
            @Html.DisplayFor(model => model.idInquilino)
        </dd>
        <dt>
            <label>Codigo Inmueble</label>
        </dt>
        <dd>
            @Html.DisplayFor(model => model.idInmueble)
        </dd>
        <dt>
            <label>Fecha Inicio</label>
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaInicio)
        </dd>
        <dt>
            <label>Fecha Final</label>
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaFin)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MontoAlquiler)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MontoAlquiler)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Vigente)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Vigente)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="submit" value="Borrar" class="btn btn-danger" />  |
        <a class="btn btn-info" asp-action="Index">Regresar</a>
    </form>
</div>

Views/Contratos/Edit.cshtml
@model Inmobiliaria.Models.Contrato

@{
    ViewData["Title"] = "Actualizar Contratos";
}

<h2>Contratos</h2>

<h4>Actualizar Datos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
             <label class="control-label">Inquilinos</label>
             <select class="form-control" name="IdInq">
                        @foreach (var item in (IList<Inquilino>)ViewBag.Inquilinos)
                        {
             @:<option @(item.idInquilino == Model.idInquilino ? "selected" : "") value="@item.idInquilino">@(item.Nombre + " " + item.Apellido)</option>
             }
             </select>
             <span asp-validation-for="idInquilino" class="text-danger"></span>
             </div>
            <div class="form-group">
                <label asp-for="idInmueble" class="control-label">Codigo Inmueble</label>
                <input asp-for="idInmueble" class="form-control" />
                <span asp-validation-for="idInmueble" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaInicio" class="control-label">Fecha Inicio</label>
                <input asp-for="FechaInicio" class="form-control" />
                <span asp-validation-for="FechaInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaFin" class="control-label">Fecha Final</label>
                <input asp-for="FechaFin" class="form-control" />
                <span asp-validation-for="FechaFin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MontoAlquiler" class="control-label"> $ Alquiler</label>
                <input asp-for="MontoAlquiler" class="form-control" />
                <span asp-validation-for="MontoAlquiler" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Vigente" /> @Html.DisplayNameFor(model => model.Vigente)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar Cambios" class="btn btn-success" />   |
                <a class="btn btn-info" asp-action="Index">Regresar a Contratos</a>
            </div>
        </form>
    </div>
</div>

Views/Contratos/Filtrados.cshtml
@model IEnumerable<Inmobiliaria.Models.Contrato>

@{ ViewData["Title"] = "Filtrados"; }

<h2>Filtrados</h2>


<table height="100" width="100" background="../imagenes/inmo.png" class="table">
    <thead>
        <tr>
            <th bgcolor="#4CAF50">Nº Contrato</th>
            <th bgcolor="#4CAF50">Inquilino</th>
            <th bgcolor="#4CAF50">Direccion Inmueble</th>
            <th bgcolor="#4CAF50">Tipo</th>
            <th bgcolor="#4CAF50">Fecha Inicio</th>
            <th bgcolor="#4CAF50">Fecha Final</th>
            <th bgcolor="#4CAF50">Importe</th>
            <th bgcolor="#4CAF50">
                @Html.DisplayNameFor(model => model.Vigente)
            </th>
            <th bgcolor="#4CAF50"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in (IList<Contrato>)ViewBag.Filtrados)
        {
<tr>
    <td>
        @item.idContrato
    </td>
    <td>
        @(item.Inquilinos.Nombre + " " + item.Inquilinos.Apellido)

    </td>
    <td>
        @item.Inmuebles.Direccion
    </td>
    <td>
        @item.Inmuebles.Tipo
    </td>
    <td>
        @item.FechaInicio
    </td>
    <td>
        @item.FechaFin
    </td>
    <td>
        @item.MontoAlquiler
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Vigente)
    </td>
    <td>
        @Html.ActionLink("Editar", "Edit", new { id = item.idContrato }) |

        @Html.ActionLink("Eliminar", "Delete", new { id = item.idContrato })
    </td>
</tr>
}
    </tbody>
</table>
<div>
    <a class="btn btn-info" asp-action="Index">Regresar</a>
</div>

Views/Contratos/Index.cshtml
@model IEnumerable<Inmobiliaria.Models.Contrato>

@{ ViewData["Title"] = "Lista de Contratos"; }

<h2>Todos los Contratos</h2>

<h4> @Html.ActionLink("Buscar Contratos Vigentes", "Busqueda", "Contratos")</h4>


<table height="100" width="100" background="../imagenes/inmo.png" class="table">
    <thead>
        <tr>
            <th bgcolor="#4CAF50">Nº Contrato</th>
            <th bgcolor="#4CAF50">
                @Html.DisplayNameFor(model => model.Inquilinos)
            </th>
            <th bgcolor="#4CAF50">
                @Html.DisplayNameFor(model => model.Inmuebles)
            </th>
            <th bgcolor="#4CAF50">Fecha Inicio</th>
            <th bgcolor="#4CAF50">Fecha Final</th>
            <th bgcolor="#4CAF50">
                @Html.DisplayNameFor(model => model.MontoAlquiler)
            </th>
            <th bgcolor="#4CAF50">
                @Html.DisplayNameFor(model => model.Vigente)
            </th>
            <th bgcolor="#4CAF50"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.idContrato)
    </td>
    <td>
        @(item.Inquilinos.Nombre + " " + item.Inquilinos.Apellido)
    </td>
    <td>
        @(item.Inmuebles.Tipo + " " + item.Inmuebles.Direccion)
    </td>
    <td>
        @*Html.DisplayFor(modelItem => item.FechaInicio)*@
        @item.FechaInicio.ToString("dd/MM/yyyy")
    </td>
    <td>
        @*Html.DisplayFor(modelItem => item.FechaFin)*@
        @item.FechaFin.ToString("dd/MM/yyyy")
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.MontoAlquiler)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Vigente)
    </td>
    <td>
        @Html.ActionLink("Editar", "Edit", new { id = item.idContrato }) |

        @Html.ActionLink("Eliminar", "Delete", new { id = item.idContrato })
    </td>
</tr>}
    </tbody>
</table>

Views/Contratos/Ver.cshtml
@model IEnumerable<Inmobiliaria.Models.Contrato>

@{ ViewData["Title"] = "Ver"; }

<h2>Ver Contratos</h2>

<p>
    <a asp-action="Create" asp-route-id="@ViewBag.Id">Agregar Nuevo Contrato</a>
</p>
<table height="100" width="100" background="../imagenes/inmo.png" class="table">
    <thead>
        <tr>
            <th bgcolor="#4CAF50">Inquilino</th>
            <th bgcolor="#4CAF50">Ubicacion Inmueble</th>
            <th bgcolor="#4CAF50">Fecha Inicio</th>
            <th bgcolor="#4CAF50">Fecha Final</th>
            <th bgcolor="#4CAF50">
                @Html.DisplayNameFor(model => model.MontoAlquiler)
            </th>
            <th bgcolor="#4CAF50">
                @Html.DisplayNameFor(model => model.Vigente)
            </th>
            <th bgcolor="#4CAF50"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Inquilinos.Nombre) @Html.DisplayFor(modelItem => item.Inquilinos.Apellido)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Inmuebles.Direccion)
                </td>
                <td>
                    @*Html.DisplayFor(modelItem => item.FechaInicio)*@
                    @item.FechaInicio.ToString("dd/MM/yyyy")
                </td>
                <td>
                    @*Html.DisplayFor(modelItem => item.FechaFin)*@
                    @item.FechaFin.ToString("dd/MM/yyyy")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MontoAlquiler)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Vigente)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", new { id = item.idContrato }) |
                    @Html.ActionLink("Ver Pagos", "Ver", "Pagos", new { id = item.idContrato }) |
                    @Html.ActionLink("Eliminar", "Delete", new { id = item.idContrato })
                </td>
            </tr>
        }
    </tbody>
</table>